services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.13.3
    depends_on:
      - elasticsearch
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - apm-server.host=0.0.0.0:8200
      - apm-server.auth.anonymous.enabled=true
      - xpack.security.enabled=false
    ports:
      - "8200:8200"

  tomcat:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - apm-server
